const shows = [
    {
        id: 1,
        title: "Antigone",
        description: "Jealousy and manipulation in Othello",
        theatre: "Girish Mancha",
        address: "456 Elm St",
        timing: "10:00 AM",
    },
    {
        id: 2,
        title: "Macbeth",
        description: "Tragic love story of Romeo and Juliet",
        theatre: "Kala Mandir",
        address: "789 Oak St",
        timing: "8:30 AM",
    },
    {
        id: 3,
        title: "Macbeth",
        description: "Conflict and morality in Antigone",
        theatre: "Minerva Theatre",
        address: "789 Oak St",
        timing: "7:00 PM",
    },
    {
        id: 4,
        title: "The Tempest",
        description: "Tragic love story of Romeo and Juliet",
        theatre: "Minerva Theatre",
        address: "456 Elm St",
        timing: "3:45 PM",
    },
    {
        id: 5,
        title: "Romeo and Juliet",
        description: "Conflict and morality in Antigone",
        theatre: "Sisir Mancha",
        address: "321 Pine St",
        timing: "7:00 PM",
    },
    {
        id: 6,
        title: "Hamlet",
        description: "Ambition and betrayal in Macbeth",
        theatre: "Academy of Fine Arts",
        address: "654 Maple St",
        timing: "8:30 AM",
    },
];
export default shows;